data_cfg:
  dataset_name: Gait3D
  dataset_root: your_path
  dataset_partition: ./datasets/Gait3D/Gait3D.json
  num_workers: 4
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Gait3D
  data_in_use: [ sils_64x44.pkl ]

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: false # true
  restore_hint: 60000
  save_name: GaitBase-Gait3D-Open_Set
  eval_func: evaluate_Gait3D
  remove_nonmated_gallery: true # Remove some gallery subjects from the data directory
  sampler:
    batch_shuffle: false
    batch_size: 24
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
  - loss_term_weight: 1.0
    type: OpenSetLoss
    num_folds: 4
    rank: 1
    score_scale: 6.0
    rank_scale: 0.2
    rank_diff_scale: 6.0
    num_parts: 16
    log_prefix: open_set

model_cfg:
  model: Baseline_OpenSet
  backbone_cfg:
    type: ResNet
    block: BasicBlock
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 3000
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestone
    - 20000
    - 40000
    - 50000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_precision float for memory reduction and speedup
  fix_BN: false
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 20000
  save_name: GaitBase-Gait3D-Open_Set
  sync_BN: true
  total_iter: 60000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 10 # min frames number for unfixed traing
    sample_type: unfixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.35
        - type: BaseSilTransform
        - type: RandomHorizontalFlip
          prob: 0.35
        - type: RandomRotate
          prob: 0.35
